import { Product, ProductCategory, ProductSpecifications } from "../types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "HP Pavilion 15 Laptop",
    description: " Powerful 15.6-inch laptop powered by Intel Core i7 processor, perfect for professionals and creators. Features stunning FHD display, backlit keyboard, and premium build quality.",
    price: 72999,
    comparePrice: 84999,
    category: "laptops",
    images: [
      "/images/products/hp-pavilion-15-1.jpg",
      "/images/products/hp-pavilion-15-2.jpg",
      "/images/products/hp-pavilion-15-3.jpg"
    ],
    specifications: {
      processor: "Intel Core i7-1355U (13th Gen)",
      ram: "16GB DDR4 RAM",
      storage: "512GB NVMe SSD",
      display: "15.6-inch FHD (1920x1080) IPS",
      graphics: "Intel Iris Xe Graphics",
      battery: "41Wh Li-ion, up to 8 hours",
      operatingSystem: "Windows 11 Home",
      warranty: "1 Year Onsite Warranty",
      weight: "1.75 kg",
      connectivity: "Wi-Fi 6, Bluetooth 5.2, USB-C, HDMI",
      ports: ["1x USB-C", "2x USB-A", "1x HDMI", "1x headphone/microphone combo"],
    },
    stock: 25,
    rating: 4.5,
    reviews: 128,
    isNew: false,
    isFeatured: true,
    brand: "HP",
    model: "Pavilion 15-eg2024",
    warranty: "1 Year Onsite Warranty",
    sku: "HP-PAV-15-i7-16GB",
    tags: ["laptop", "hp", "intel", "windows"],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Dell Inspiron 14 Plus",
    description: "14-inch compact laptop with Intel Core i5 processor, perfect for work-from-home professionals. Lightweight design with all-day battery life.",
    price: 59999,
    comparePrice: 69999,
    category: "laptops",
    images: [
      "/images/products/dell-inspiron-14-1.jpg",
      "/images/products/dell-inspiron-14-2.jpg"
    ],
    specifications: {
      processor: "Intel Core i5-1340P (13th Gen)",
      ram: "8GB DDR4 RAM",
      storage: "512GB NVMe SSD",
      display: "14-inch FHD (1920x1080) WVA",
      graphics: "Intel Iris Xe Graphics",
      battery: "54Wh, up to 10 hours",
      operatingSystem: "Windows 11 Home",
      warranty: "1 Year Premium Support",
      weight: "1.54 kg",
      connectivity: "Wi-Fi 6E, Bluetooth 5.2",
      ports: ["2x USB-A", "1x USB-C", "1x HDMI 1.4"],
    },
    stock: 40,
    rating: 4.3,
    reviews: 89,
    isNew: true,
    isFeatured: true,
    brand: "Dell",
    model: "Inspiron 14 Plus 7430",
    warranty: "1 Year Premium Support",
    sku: "DELL-INS-14-i5-8GB",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Lenovo ThinkPad E14",
    description: "Business-grade 14-inch laptop with Intel Core i7, spill-resistant keyboard, and robust security features. Built for enterprise reliability.",
    price: 79999,
    comparePrice: 92999,
    category: "laptops",
    images: [
      "/images/products/lenovo-thinkpad-e14-1.jpg",
      "/images/products/lenovo-thinkpad-e14-2.jpg"
    ],
    specifications: {
      processor: "Intel Core i7-1365U (13th Gen)",
      ram: "16GB DDR4 RAM",
      storage: "512GB SSD",
      display: "14-inch FHD (1920x1080) IPS",
      graphics: "Intel Iris Xe Graphics",
      battery: "45Wh, up to 9 hours",
      operatingSystem: "Windows 11 Pro",
      warranty: "1 Year Premier Support",
      weight: "1.65 kg",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      ports: ["USB-C", "2x USB-A", "HDMI", "RJ45"],
    },
    stock: 30,
    rating: 4.6,
    reviews: 156,
    isFeatured: true,
    brand: "Lenovo",
    model: "ThinkPad E14 Gen 5",
    warranty: "1 Year Premier Support",
    sku: "LEN-ThkP-E14-i7",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    name: "ASUS ROG Strix G16 Gaming Laptop",
    description: "Ultimate gaming laptop with Intel Core i9, RTX 4070 graphics, 165Hz display. Features per-key RGB keyboard and advanced cooling system.",
    price: 169999,
    comparePrice: 199999,
    category: "laptops",
    images: [
      "/images/products/asus-rog-strix-1.jpg",
      "/images/products/asus-rog-strix-2.jpg"
    ],
    specifications: {
      processor: "Intel Core i9-13980HX",
      ram: "16GB DDR5 RAM",
      storage: "1TB NVMe SSD",
      display: "16-inch FHD (1920x1200) 165Hz",
      graphics: "NVIDIA GeForce RTX 4070 8GB",
      battery: "90Wh",
      operatingSystem: "Windows 11 Home",
      warranty: "2 Year Global Warranty",
      weight: "2.5 kg",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      ports: ["1x Thunderbolt 4", "2x USB-A", "HDMI 2.1"],
    },
    stock: 15,
    rating: 4.8,
    reviews: 234,
    isNew: true,
    isFeatured: true,
    brand: "ASUS",
    model: "ROG Strix G16 G614JI",
    warranty: "2 Year Global Warranty",
    sku: "ASUS-ROG-G16-i9",
    tags: ["gaming", "laptop", "rtx"],
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "5",
    name: "HP Pavilion Desktop M01-F3014",
    description: "Reliable desktop PC with Intel Core i5, 8GB RAM, 512GB SSD. Perfect for home office and everyday computing needs.",
    price: 44999,
    comparePrice: 52999,
    category: "desktops",
    images: [
      "/images/products/hp-pavilion-desktop-1.jpg"
    ],
    specifications: {
      processor: "Intel Core i5-13400 (13th Gen)",
      ram: "8GB DDR4 RAM",
      storage: "512GB SSD",
      graphics: "Intel UHD Graphics 730",
      operatingSystem: "Windows 11 Home",
      warranty: "1 Year Onsite Warranty",
      weight: "4.2 kg",
      connectivity: "Wi-Fi, Bluetooth",
      ports: ["4x USB-A", "HDMI", "VGA"],
    },
    stock: 20,
    rating: 4.2,
    reviews: 67,
    isFeatured: false,
    brand: "HP",
    model: "Pavilion Desktop M01-F3014",
    warranty: "1 Year Onsite Warranty",
    sku: "HP-DESK-i5-8GB",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "6",
    name: "Dell Inspiron 24 All-in-One",
    description: "24-inch all-in-one desktop with Intel Core i7, stunning FHD display, and wireless connectivity. Space-saving design for modern homes.",
    price: 74999,
    comparePrice: 89999,
    category: "desktops",
    images: [
      "/images/products/dell-aio-24-1.jpg"
    ],
    specifications: {
      processor: "Intel Core i7-1355U",
      ram: "16GB DDR4 RAM",
      storage: "512GB SSD + 1TB HDD",
      display: "23.8-inch FHD (1920x1080)",
      graphics: "Intel Iris Xe Graphics",
      operatingSystem: "Windows 11 Home",
      warranty: "1 Year Premium Support",
      weight: "5.4 kg",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      ports: ["3x USB-A", "1x USB-C", "HDMI"],
    },
    stock: 12,
    rating: 4.4,
    reviews: 45,
    isNew: false,
    isFeatured: true,
    brand: "Dell",
    model: "Inspiron 24 5420",
    warranty: "1 Year Premium Support",
    sku: "DELL-AIO-i7-16GB",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "7",
    name: "Logitech MX Master 3S Mouse",
    description: "Premium wireless mouse with 8000 DPI sensor, quiet clicks, and MagSpeed scroll wheel. Perfect for professionals.",
    price: 8999,
    comparePrice: 9999,
    category: "computer-accessories",
    images: [
      "/images/products/logitech-mx-master-1.jpg",
      "/images/products/logitech-mx-master-2.jpg"
    ],
    specifications: {
      connectivity: "Bluetooth, USB Receiver",
      battery: "70 days on full charge",
      warranty: "2 Year Limited Hardware Warranty",
      weight: "141 g",
      additionalSpecs: {
        "Sensor": "8000 DPI",
        "Buttons": "7",
        "Scroll Wheel": "MagSpeed Electromagnetic",
      }
    },
    stock: 50,
    rating: 4.7,
    reviews: 312,
    isFeatured: true,
    brand: "Logitech",
    model: "MX Master 3S",
    warranty: "2 Year Limited Hardware Warranty",
    sku: "LOG-MXM-3S",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "8",
    name: "Logitech MX Keys Mini Keyboard",
    description: "Compact wireless keyboard with smart backlighting, perfect keys, and multi-device support.",
    price: 6999,
    comparePrice: 7999,
    category: "computer-accessories",
    images: [
      "/images/products/logitech-mx-keys-1.jpg"
    ],
    specifications: {
      connectivity: "Bluetooth, USB Receiver",
      battery: "10 days with backlighting",
      warranty: "2 Year Limited Hardware Warranty",
      weight: "506.4 g",
      additionalSpecs: {
        "Keys": "Perfect Stroke keys",
        "Backlighting": "Smart backlighting",
        "Devices": "Up to 3 devices",
      }
    },
    stock: 45,
    rating: 4.6,
    reviews: 189,
    isNew: false,
    isFeatured: true,
    brand: "Logitech",
    model: "MX Keys Mini",
    warranty: "2 Year Limited Hardware Warranty",
    sku: "LOG-MXK-MINI",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "9",
    name: "Logitech C920x Pro HD Webcam",
    description: "Full HD 1080p webcam with autofocus, auto light correction, and stereo audio. Perfect for video calls and streaming.",
    price: 4999,
    comparePrice: 5999,
    category: "computer-accessories",
    images: [
      "/images/products/logitech-c920x-1.jpg"
    ],
    specifications: {
      resolution: "1080p at 30fps, 720p at 60fps",
      connectivity: "USB 2.0",
      warranty: "1 Year Limited Hardware Warranty",
      weight: "162 g",
      additionalSpecs: {
        "Focus": "Autofocus",
        "FOV": "78°",
        "Microphone": "Stereo",
      }
    },
    stock: 60,
    rating: 4.5,
    reviews: 423,
    isFeatured: false,
    brand: "Logitech",
    model: "C920x Pro HD",
    warranty: "1 Year Limited Hardware Warranty",
    sku: "LOG-C920X",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "10",
    name: "Sony WH-1000XM5 Headphones",
    description: "Industry-leading noise cancellation with 30-hour battery life and exceptional audio quality.",
    price: 27999,
    comparePrice: 32999,
    category: "computer-accessories",
    images: [
      "/images/products/sony-xm5-1.jpg",
      "/images/products/sony-xm5-2.jpg"
    ],
    specifications: {
      battery: "30 hours (NC on), 40 hours (NC off)",
      charging: "3.5 hours",
      warranty: "1 Year Warranty",
      weight: "250 g",
      additionalSpecs: {
        "Driver": "30mm",
        "Frequency": "4Hz-40,000Hz",
        "Bluetooth": "5.2",
        "Codecs": "LDAC, AAC, SBC",
      }
    },
    stock: 35,
    rating: 4.8,
    reviews: 567,
    isNew: false,
    isFeatured: true,
    brand: "Sony",
    model: "WH-1000XM5",
    warranty: "1 Year Warranty",
    sku: "SON-WH-1000XM5",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "11",
    name: "TP-Link Archer AX73 Router",
    description: "AX5400 dual-band Wi-Fi 6 router with 8 antennas, perfect for large homes and gaming.",
    price: 7999,
    comparePrice: 9999,
    category: "networking-equipment",
    images: [
      "/images/products/tp-link-ax73-1.jpg"
    ],
    specifications: {
      speed: "5400 Mbps (4804 + 574 Mbps)",
      processor: "1.5GHz Tri-Core",
      ram: "256MB",
      ports: "4x Gigabit LAN, 1x Gigabit WAN, 1x USB 3.0",
      warranty: "3 Year Warranty",
      weight: "600 g",
      additionalSpecs: {
        "Standards": "Wi-Fi 6 (802.11ax)",
        "Bands": "Dual Band",
        "MU-MIMO": "4x4 MU-MIMO",
        "Beamforming": "Explicit Beamforming",
      }
    },
    stock: 40,
    rating: 4.4,
    reviews: 234,
    isFeatured: true,
    brand: "TP-Link",
    model: "Archer AX73",
    warranty: "3 Year Warranty",
    sku: "TPL-AX73",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "12",
    name: "Cisco SG110D-16 Switch",
    description: "16-port Gigabit unmanaged switch, plug-and-play solution for small business networks.",
    price: 4999,
    comparePrice: 5999,
    category: "networking-equipment",
    images: [
      "/images/products/cisco-switch-1.jpg"
    ],
    specifications: {
      ports: "16x Gigabit Ethernet",
      switching: "32 Gbps",
      power: "Internal, 110-240V",
      warranty: "Lifetime Limited Hardware Warranty",
      weight: "1.0 kg",
      additionalSpecs: {
        "Type": "Unmanaged",
        "Jumbo Frames": "Up to 9216 bytes",
        "QoS": "802.1p CoS",
        "Fan": "Fanless",
      }
    },
    stock: 25,
    rating: 4.5,
    reviews: 78,
    isFeatured: false,
    brand: "Cisco",
    model: "SG110D-16",
    warranty: "Lifetime Limited Hardware Warranty",
    sku: "CIS-SG110-16",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "13",
    name: "Microsoft Windows 11 Pro",
    description: "Windows 11 Pro operating system with advanced security and productivity features.",
    price: 8499,
    comparePrice: 9999,
    category: "software",
    images: [
      "/images/products/windows-11-pro-1.jpg"
    ],
    specifications: {
      license: "Digital License",
      version: "Pro",
      systemRequirements: "4GB RAM, 64GB storage, TPM 2.0",
      warranty: "1 Year Warranty on Key",
      additionalSpecs: {
        "BitLocker": "Yes",
        "Remote Desktop": "Yes",
        "Hyper-V": "Yes",
        "Assigned Access": "Yes",
      }
    },
    stock: 100,
    rating: 4.6,
    reviews: 156,
    isFeatured: true,
    brand: "Microsoft",
    model: "Windows 11 Pro",
    warranty: "1 Year Warranty on Key",
    sku: "MS-W11-PRO",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "14",
    name: "Kaspersky Total Security",
    description: "Comprehensive antivirus with password manager, VPN, and parental controls. Protects up to 5 devices.",
    price: 1999,
    comparePrice: 2999,
    category: "software",
    images: [
      "/images/products/kaspersky-total-1.jpg"
    ],
    specifications: {
      devices: "5 devices",
      duration: "1 Year",
      features: "Antivirus, VPN, Password Manager, Parental Control",
      warranty: "1 Year Subscription",
      additionalSpecs: {
        "Real-time Protection": "Yes",
        "Payment Protection": "Yes",
        "Webcam Protection": "Yes",
        "File Encryption": "Yes",
      }
    },
    stock: 150,
    rating: 4.3,
    reviews: 423,
    isFeatured: false,
    brand: "Kaspersky",
    model: "Total Security 2024",
    warranty: "1 Year Subscription",
    sku: "KAS-TOT-24",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "15",
    name: "HP LaserJet Pro M108w",
    description: "Compact wireless laser printer with fast print speeds and high-quality output. Perfect for home offices.",
    price: 12999,
    comparePrice: 15999,
    category: "printers-scanners",
    images: [
      "/images/products/hp-laserjet-1.jpg"
    ],
    specifications: {
      printSpeed: "20 ppm",
      resolution: "1200 x 1200 dpi",
      connectivity: "Wi-Fi, USB 2.0",
      dutyCycle: "10000 pages/month",
      warranty: "1 Year Onsite Warranty",
      weight: "5.3 kg",
      additionalSpecs: {
        "First Page": "8.3 seconds",
        "Input": "150 sheets",
        "Output": "100 sheets",
        "Technology": "Laser",
      }
    },
    stock: 30,
    rating: 4.4,
    reviews: 189,
    isFeatured: true,
    brand: "HP",
    model: "LaserJet Pro M108w",
    warranty: "1 Year Onsite Warranty",
    sku: "HP-LJ-M108W",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "16",
    name: "Epson Workforce ES-400 II Scanner",
    description: "Fast duplex document scanner with auto document feeder. Perfect for small business document management.",
    price: 22999,
    comparePrice: 27999,
    category: "printers-scanners",
    images: [
      "/images/products/epson-es400-1.jpg"
    ],
    specifications: {
      scanSpeed: "35 ppm (simplex), 70 ipm (duplex)",
      resolution: "600 x 600 dpi",
      connectivity: "USB 3.0, Wi-Fi",
      adf: "50 sheets",
      warranty: "1 Year Standard Warranty",
      weight: "3.4 kg",
      additionalSpecs: {
        "Duty Cycle": "4000 pages/day",
        "Scanning": "Duplex",
        "OCR": "Yes",
        "Drivers": "TWAIN, WIA, ICA",
      }
    },
    stock: 20,
    rating: 4.5,
    reviews: 67,
    isNew: true,
    isFeatured: true,
    brand: "Epson",
    model: "Workforce ES-400 II",
    warranty: "1 Year Standard Warranty",
    sku: "EP-ES400II",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "17",
    name: "Razer DeathAdder V3 Pro",
    description: "Ultra-lightweight wireless gaming mouse with 30K DPI sensor and optical switches.",
    price: 12999,
    comparePrice: 15999,
    category: "gaming-gear",
    images: [
      "/images/products/razer-deathadder-1.jpg"
    ],
    specifications: {
      sensor: "30000 DPI Focus Pro Optical",
      switches: "Optical Mouse Switches Gen-3",
      battery: "90 hours",
      weight: "63 g",
      warranty: "2 Year Warranty",
      additionalSpecs: {
        "Polling Rate": "4000 Hz",
        "Buttons": "8 programmable",
        "RGB": "Razer Chroma RGB",
        "Cable": "Razer Speedflex",
      }
    },
    stock: 35,
    rating: 4.8,
    reviews: 345,
    isNew: true,
    isFeatured: true,
    brand: "Razer",
    model: "DeathAdder V3 Pro",
    warranty: "2 Year Warranty",
    sku: "RAZ-DA-V3-PRO",
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "18",
    name: "Razer BlackShark V2 Pro",
    description: "Professional esports headset with THX Audio and active noise cancellation.",
    price: 16999,
    comparePrice: 19999,
    category: "gaming-gear",
    images: [
      "/images/products/razer-blackshark-1.jpg"
    ],
    specifications: {
      drivers: "50mm Titanium",
      frequency: "20Hz - 20kHz",
      battery: "70 hours (wireless)",
      weight: "262 g",
      warranty: "2 Year Warranty",
      additionalSpecs: {
        "Microphone": "HyperClear Super Wideband",
        "THX": "THX Spatial Audio",
        "ANC": "Active Noise Cancellation",
        "Connection": "2.4GHz + Bluetooth 5.2",
      }
    },
    stock: 25,
    rating: 4.7,
    reviews: 234,
    isFeatured: true,
    brand: "Razer",
    model: "BlackShark V2 Pro",
    warranty: "2 Year Warranty",
    sku: "RAZ-BSH-V2-PRO",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "19",
    name: "APC Back-UPS 600VA",
    description: "Reliable UPS with automatic voltage regulation. Perfect for protecting your computer and peripherals.",
    price: 3999,
    comparePrice: 4999,
    category: "office-equipment",
    images: [
      "/images/products/apc-ups-1.jpg"
    ],
    specifications: {
      capacity: "600VA / 330W",
      output: "230V",
      batteryType: "Valve-regulated Lead Acid",
      transferTime: "8 ms typical",
      weight: "5.7 kg",
      warranty: "2 Year Warranty",
      additionalSpecs: {
        "Outlets": "3x Battery + 3x Surge",
        "Waveform": "Stepped Approximation",
        "Protection": "Surge, Brownout, Short Circuit",
        "Indicator": "LED Status",
      }
    },
    stock: 50,
    rating: 4.5,
    reviews: 312,
    isFeatured: false,
    brand: "APC",
    model: "Back-UPS 600VA",
    warranty: "2 Year Warranty",
    sku: "APC-BU600",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "20",
    name: "Samsung 980 PRO 1TB SSD",
    description: "Blazing fast PCIe 4.0 NVMe SSD with up to 7000MB/s read speed. Perfect for gaming and content creation.",
    price: 11999,
    comparePrice: 14999,
    category: "computer-accessories",
    images: [
      "/images/products/samsung-980pro-1.jpg"
    ],
    specifications: {
      readSpeed: "7000 MB/s",
      writeSpeed: "5100 MB/s",
      interface: "PCIe 4.0 NVMe",
      formFactor: "M.2 2280",
      warranty: "5 Year Limited Warranty",
      weight: "9 g",
      additionalSpecs: {
        "Capacity": "1TB",
        "Random Read": "1050K IOPS",
        "Random Write": "1400K IOPS",
        "TBW": "600 TB",
      }
    },
    stock: 60,
    rating: 4.9,
    reviews: 678,
    isNew: false,
    isFeatured: true,
    brand: "Samsung",
    model: "980 PRO 1TB",
    warranty: "5 Year Limited Warranty",
    sku: "SAM-980PRO-1TB",
    createdAt: new Date("2024-01-05"),
  },
];

export const MOCK_CATEGORIES = [
  { id: "laptops", name: "Laptops", slug: "laptops", productCount: 4 },
  { id: "desktops", name: "Desktops", slug: "desktops", productCount: 2 },
  { id: "computer-accessories", name: "Computer Accessories", slug: "computer-accessories", productCount: 6 },
  { id: "networking-equipment", name: "Networking Equipment", slug: "networking-equipment", productCount: 2 },
  { id: "software", name: "Software", slug: "software", productCount: 2 },
  { id: "printers-scanners", name: "Printers & Scanners", slug: "printers-scanners", productCount: 2 },
  { id: "gaming-gear", name: "Gaming Gear", slug: "gaming-gear", productCount: 2 },
  { id: "office-equipment", name: "Office Equipment", slug: "office-equipment", productCount: 1 },
] as const;

export const MOCK_REVIEWS = [
  {
    id: "r1",
    productId: "1",
    userId: "u1",
    userName: "Rahul Sharma",
    rating: 5,
    title: "Excellent laptop for professionals",
    comment: "Been using this laptop for 3 months now. Performance is great, battery lasts full work day. Display is crisp and clear. Highly recommended for business users.",
    verified: true,
    helpful: 45,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "r2",
    productId: "1",
    userId: "u2",
    userName: "Priya Patel",
    rating: 4,
    title: "Great but pricey",
    comment: "Solid build quality and performance. The price is on higher side but worth investment. Keyboard feels comfortable for long typing sessions.",
    verified: true,
    helpful: 23,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "r3",
    productId: "7",
    userId: "u3",
    userName: "Aditya Kumar",
    rating: 5,
    title: "Best mouse I've ever used",
    comment: "The scroll wheel is incredibly smooth. Quiet clicks are a blessing for office environment. Connects seamlessly with multiple devices.",
    verified: true,
    helpful: 67,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "r4",
    productId: "11",
    userId: "u4",
    userName: "Vikram Singh",
    rating: 4,
    title: "Great coverage for large home",
    comment: "Covers my 3BHK apartment easily. Gaming mode works well, no lag during online gaming. Setup was straightforward.",
    verified: true,
    helpful: 34,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "r5",
    productId: "17",
    userId: "u5",
    userName: "Karthik R",
    rating: 5,
    title: "Pro-level mouse at pro-level price",
    comment: "Lightweight but feels premium. 30K DPI is overkill but amazing. Optical switches feel snappy. Best gaming mouse I've used.",
    verified: true,
    helpful: 89,
    createdAt: new Date("2024-03-20"),
  },
];